package rpg;

public class InvalidItemException extends RuntimeException {

	/**
	 * Java suggests giving every exception a unique identifier,
	 * this one has been auto generated by Eclipse.
	 */
	private static final long serialVersionUID = -8259006034800131332L;
	
	/**
	 * Initialises a new invalid item exception with the given message.
	 * @param message
	 * 		  Message string to be passed to the superclass RuntimeException.
	 */
	public InvalidItemException(String message){
		super(message);
	}

}
