package rpg.exception;

/**
 * Created by elias on 15/07/2017.
 */
public class InvalidNameException extends RuntimeException {

    /**
     * Java suggests giving every exception a unique identifier,
     * this one has been auto generated by Intellij IDEA.
     */
    private static final long serialVersionUID = 6382963446988079486L;

    /**
     * Initialises a new invalid name exception with the given message.
     *
     * @param message Message string to be passed to the superclass RuntimeException.
     */
    public InvalidNameException(String message) {
        super(message);
    }

}
